//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEDDProyecto.WebServiceServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Volumen/", ConfigurationName="WebServiceServer.ServiciosWeb")]
    public interface ServiciosWeb {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Volumen/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/CalcularVolumenEsferaRequest", ReplyAction="http://Volumen/ServiciosWeb/CalcularVolumenEsferaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse CalcularVolumenEsfera(ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/CalcularVolumenEsferaRequest", ReplyAction="http://Volumen/ServiciosWeb/CalcularVolumenEsferaResponse")]
        System.Threading.Tasks.Task<ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse> CalcularVolumenEsferaAsync(ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularVolumenEsfera", WrapperNamespace="http://Volumen/", IsWrapped=true)]
    public partial class CalcularVolumenEsferaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Radio;
        
        public CalcularVolumenEsferaRequest() {
        }
        
        public CalcularVolumenEsferaRequest(double Radio) {
            this.Radio = Radio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularVolumenEsferaResponse", WrapperNamespace="http://Volumen/", IsWrapped=true)]
    public partial class CalcularVolumenEsferaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public CalcularVolumenEsferaResponse() {
        }
        
        public CalcularVolumenEsferaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWebChannel : ClienteEDDProyecto.WebServiceServer.ServiciosWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWebClient : System.ServiceModel.ClientBase<ClienteEDDProyecto.WebServiceServer.ServiciosWeb>, ClienteEDDProyecto.WebServiceServer.ServiciosWeb {
        
        public ServiciosWebClient() {
        }
        
        public ServiciosWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse ClienteEDDProyecto.WebServiceServer.ServiciosWeb.CalcularVolumenEsfera(ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest request) {
            return base.Channel.CalcularVolumenEsfera(request);
        }
        
        public double CalcularVolumenEsfera(double Radio) {
            ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest inValue = new ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest();
            inValue.Radio = Radio;
            ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse retVal = ((ClienteEDDProyecto.WebServiceServer.ServiciosWeb)(this)).CalcularVolumenEsfera(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse> ClienteEDDProyecto.WebServiceServer.ServiciosWeb.CalcularVolumenEsferaAsync(ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest request) {
            return base.Channel.CalcularVolumenEsferaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaResponse> CalcularVolumenEsferaAsync(double Radio) {
            ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest inValue = new ClienteEDDProyecto.WebServiceServer.CalcularVolumenEsferaRequest();
            inValue.Radio = Radio;
            return ((ClienteEDDProyecto.WebServiceServer.ServiciosWeb)(this)).CalcularVolumenEsferaAsync(inValue);
        }
    }
}
