//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCliente.servicioweb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Volumen/", ConfigurationName="servicioweb.VolumenEsfera")]
    public interface VolumenEsfera {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/agregarcarritoRequest", ReplyAction="http://Volumen/VolumenEsfera/agregarcarritoResponse")]
        ProyectoCliente.servicioweb.agregarcarritoResponse agregarcarrito(ProyectoCliente.servicioweb.agregarcarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/agregarcarritoRequest", ReplyAction="http://Volumen/VolumenEsfera/agregarcarritoResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcarritoResponse> agregarcarritoAsync(ProyectoCliente.servicioweb.agregarcarritoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento User del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/LoginRequest", ReplyAction="http://Volumen/VolumenEsfera/LoginResponse")]
        ProyectoCliente.servicioweb.LoginResponse Login(ProyectoCliente.servicioweb.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/LoginRequest", ReplyAction="http://Volumen/VolumenEsfera/LoginResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.LoginResponse> LoginAsync(ProyectoCliente.servicioweb.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/CatalogoRequest", ReplyAction="http://Volumen/VolumenEsfera/CatalogoResponse")]
        ProyectoCliente.servicioweb.CatalogoResponse Catalogo(ProyectoCliente.servicioweb.CatalogoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/CatalogoRequest", ReplyAction="http://Volumen/VolumenEsfera/CatalogoResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.CatalogoResponse> CatalogoAsync(ProyectoCliente.servicioweb.CatalogoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/dotcomprasRequest", ReplyAction="http://Volumen/VolumenEsfera/dotcomprasResponse")]
        ProyectoCliente.servicioweb.dotcomprasResponse dotcompras(ProyectoCliente.servicioweb.dotcomprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/dotcomprasRequest", ReplyAction="http://Volumen/VolumenEsfera/dotcomprasResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.dotcomprasResponse> dotcomprasAsync(ProyectoCliente.servicioweb.dotcomprasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/agregarcompraRequest", ReplyAction="http://Volumen/VolumenEsfera/agregarcompraResponse")]
        ProyectoCliente.servicioweb.agregarcompraResponse agregarcompra(ProyectoCliente.servicioweb.agregarcompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/agregarcompraRequest", ReplyAction="http://Volumen/VolumenEsfera/agregarcompraResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcompraResponse> agregarcompraAsync(ProyectoCliente.servicioweb.agregarcompraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/carritodotRequest", ReplyAction="http://Volumen/VolumenEsfera/carritodotResponse")]
        ProyectoCliente.servicioweb.carritodotResponse carritodot(ProyectoCliente.servicioweb.carritodotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/carritodotRequest", ReplyAction="http://Volumen/VolumenEsfera/carritodotResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.carritodotResponse> carritodotAsync(ProyectoCliente.servicioweb.carritodotRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/comprarRequest", ReplyAction="http://Volumen/VolumenEsfera/comprarResponse")]
        ProyectoCliente.servicioweb.comprarResponse comprar(ProyectoCliente.servicioweb.comprarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/VolumenEsfera/comprarRequest", ReplyAction="http://Volumen/VolumenEsfera/comprarResponse")]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.comprarResponse> comprarAsync(ProyectoCliente.servicioweb.comprarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarcarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarcarrito", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.agregarcarritoRequestBody Body;
        
        public agregarcarritoRequest() {
        }
        
        public agregarcarritoRequest(ProyectoCliente.servicioweb.agregarcarritoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agregarcarritoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long arg2;
        
        public agregarcarritoRequestBody() {
        }
        
        public agregarcarritoRequestBody(string arg0, int arg1, long arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarcarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarcarritoResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.agregarcarritoResponseBody Body;
        
        public agregarcarritoResponse() {
        }
        
        public agregarcarritoResponse(ProyectoCliente.servicioweb.agregarcarritoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class agregarcarritoResponseBody {
        
        public agregarcarritoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ProyectoCliente.servicioweb.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string User, string Pass) {
            this.User = User;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ProyectoCliente.servicioweb.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Catalogo", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.CatalogoRequestBody Body;
        
        public CatalogoRequest() {
        }
        
        public CatalogoRequest(ProyectoCliente.servicioweb.CatalogoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CatalogoRequestBody {
        
        public CatalogoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogoResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.CatalogoResponseBody Body;
        
        public CatalogoResponse() {
        }
        
        public CatalogoResponse(ProyectoCliente.servicioweb.CatalogoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CatalogoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CatalogoResponseBody() {
        }
        
        public CatalogoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dotcomprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dotcompras", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.dotcomprasRequestBody Body;
        
        public dotcomprasRequest() {
        }
        
        public dotcomprasRequest(ProyectoCliente.servicioweb.dotcomprasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class dotcomprasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public dotcomprasRequestBody() {
        }
        
        public dotcomprasRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dotcomprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dotcomprasResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.dotcomprasResponseBody Body;
        
        public dotcomprasResponse() {
        }
        
        public dotcomprasResponse(ProyectoCliente.servicioweb.dotcomprasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class dotcomprasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public dotcomprasResponseBody() {
        }
        
        public dotcomprasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarcompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarcompra", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.agregarcompraRequestBody Body;
        
        public agregarcompraRequest() {
        }
        
        public agregarcompraRequest(ProyectoCliente.servicioweb.agregarcompraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agregarcompraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long arg2;
        
        public agregarcompraRequestBody() {
        }
        
        public agregarcompraRequestBody(string arg0, int arg1, long arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarcompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarcompraResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.agregarcompraResponseBody Body;
        
        public agregarcompraResponse() {
        }
        
        public agregarcompraResponse(ProyectoCliente.servicioweb.agregarcompraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class agregarcompraResponseBody {
        
        public agregarcompraResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class carritodotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="carritodot", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.carritodotRequestBody Body;
        
        public carritodotRequest() {
        }
        
        public carritodotRequest(ProyectoCliente.servicioweb.carritodotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class carritodotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public carritodotRequestBody() {
        }
        
        public carritodotRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class carritodotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="carritodotResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.carritodotResponseBody Body;
        
        public carritodotResponse() {
        }
        
        public carritodotResponse(ProyectoCliente.servicioweb.carritodotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class carritodotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public carritodotResponseBody() {
        }
        
        public carritodotResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprar", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.comprarRequestBody Body;
        
        public comprarRequest() {
        }
        
        public comprarRequest(ProyectoCliente.servicioweb.comprarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class comprarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public comprarRequestBody() {
        }
        
        public comprarRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprarResponse", Namespace="http://Volumen/", Order=0)]
        public ProyectoCliente.servicioweb.comprarResponseBody Body;
        
        public comprarResponse() {
        }
        
        public comprarResponse(ProyectoCliente.servicioweb.comprarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class comprarResponseBody {
        
        public comprarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VolumenEsferaChannel : ProyectoCliente.servicioweb.VolumenEsfera, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VolumenEsferaClient : System.ServiceModel.ClientBase<ProyectoCliente.servicioweb.VolumenEsfera>, ProyectoCliente.servicioweb.VolumenEsfera {
        
        public VolumenEsferaClient() {
        }
        
        public VolumenEsferaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VolumenEsferaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VolumenEsferaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VolumenEsferaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.agregarcarritoResponse ProyectoCliente.servicioweb.VolumenEsfera.agregarcarrito(ProyectoCliente.servicioweb.agregarcarritoRequest request) {
            return base.Channel.agregarcarrito(request);
        }
        
        public void agregarcarrito(string arg0, int arg1, long arg2) {
            ProyectoCliente.servicioweb.agregarcarritoRequest inValue = new ProyectoCliente.servicioweb.agregarcarritoRequest();
            inValue.Body = new ProyectoCliente.servicioweb.agregarcarritoRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            ProyectoCliente.servicioweb.agregarcarritoResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).agregarcarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcarritoResponse> ProyectoCliente.servicioweb.VolumenEsfera.agregarcarritoAsync(ProyectoCliente.servicioweb.agregarcarritoRequest request) {
            return base.Channel.agregarcarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcarritoResponse> agregarcarritoAsync(string arg0, int arg1, long arg2) {
            ProyectoCliente.servicioweb.agregarcarritoRequest inValue = new ProyectoCliente.servicioweb.agregarcarritoRequest();
            inValue.Body = new ProyectoCliente.servicioweb.agregarcarritoRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).agregarcarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.LoginResponse ProyectoCliente.servicioweb.VolumenEsfera.Login(ProyectoCliente.servicioweb.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string User, string Pass) {
            ProyectoCliente.servicioweb.LoginRequest inValue = new ProyectoCliente.servicioweb.LoginRequest();
            inValue.Body = new ProyectoCliente.servicioweb.LoginRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            ProyectoCliente.servicioweb.LoginResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.LoginResponse> ProyectoCliente.servicioweb.VolumenEsfera.LoginAsync(ProyectoCliente.servicioweb.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.LoginResponse> LoginAsync(string User, string Pass) {
            ProyectoCliente.servicioweb.LoginRequest inValue = new ProyectoCliente.servicioweb.LoginRequest();
            inValue.Body = new ProyectoCliente.servicioweb.LoginRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.CatalogoResponse ProyectoCliente.servicioweb.VolumenEsfera.Catalogo(ProyectoCliente.servicioweb.CatalogoRequest request) {
            return base.Channel.Catalogo(request);
        }
        
        public string Catalogo() {
            ProyectoCliente.servicioweb.CatalogoRequest inValue = new ProyectoCliente.servicioweb.CatalogoRequest();
            inValue.Body = new ProyectoCliente.servicioweb.CatalogoRequestBody();
            ProyectoCliente.servicioweb.CatalogoResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).Catalogo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.CatalogoResponse> ProyectoCliente.servicioweb.VolumenEsfera.CatalogoAsync(ProyectoCliente.servicioweb.CatalogoRequest request) {
            return base.Channel.CatalogoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.CatalogoResponse> CatalogoAsync() {
            ProyectoCliente.servicioweb.CatalogoRequest inValue = new ProyectoCliente.servicioweb.CatalogoRequest();
            inValue.Body = new ProyectoCliente.servicioweb.CatalogoRequestBody();
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).CatalogoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.dotcomprasResponse ProyectoCliente.servicioweb.VolumenEsfera.dotcompras(ProyectoCliente.servicioweb.dotcomprasRequest request) {
            return base.Channel.dotcompras(request);
        }
        
        public string dotcompras(string arg0) {
            ProyectoCliente.servicioweb.dotcomprasRequest inValue = new ProyectoCliente.servicioweb.dotcomprasRequest();
            inValue.Body = new ProyectoCliente.servicioweb.dotcomprasRequestBody();
            inValue.Body.arg0 = arg0;
            ProyectoCliente.servicioweb.dotcomprasResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).dotcompras(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.dotcomprasResponse> ProyectoCliente.servicioweb.VolumenEsfera.dotcomprasAsync(ProyectoCliente.servicioweb.dotcomprasRequest request) {
            return base.Channel.dotcomprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.dotcomprasResponse> dotcomprasAsync(string arg0) {
            ProyectoCliente.servicioweb.dotcomprasRequest inValue = new ProyectoCliente.servicioweb.dotcomprasRequest();
            inValue.Body = new ProyectoCliente.servicioweb.dotcomprasRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).dotcomprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.agregarcompraResponse ProyectoCliente.servicioweb.VolumenEsfera.agregarcompra(ProyectoCliente.servicioweb.agregarcompraRequest request) {
            return base.Channel.agregarcompra(request);
        }
        
        public void agregarcompra(string arg0, int arg1, long arg2) {
            ProyectoCliente.servicioweb.agregarcompraRequest inValue = new ProyectoCliente.servicioweb.agregarcompraRequest();
            inValue.Body = new ProyectoCliente.servicioweb.agregarcompraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            ProyectoCliente.servicioweb.agregarcompraResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).agregarcompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcompraResponse> ProyectoCliente.servicioweb.VolumenEsfera.agregarcompraAsync(ProyectoCliente.servicioweb.agregarcompraRequest request) {
            return base.Channel.agregarcompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.agregarcompraResponse> agregarcompraAsync(string arg0, int arg1, long arg2) {
            ProyectoCliente.servicioweb.agregarcompraRequest inValue = new ProyectoCliente.servicioweb.agregarcompraRequest();
            inValue.Body = new ProyectoCliente.servicioweb.agregarcompraRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).agregarcompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.carritodotResponse ProyectoCliente.servicioweb.VolumenEsfera.carritodot(ProyectoCliente.servicioweb.carritodotRequest request) {
            return base.Channel.carritodot(request);
        }
        
        public string carritodot(string arg0) {
            ProyectoCliente.servicioweb.carritodotRequest inValue = new ProyectoCliente.servicioweb.carritodotRequest();
            inValue.Body = new ProyectoCliente.servicioweb.carritodotRequestBody();
            inValue.Body.arg0 = arg0;
            ProyectoCliente.servicioweb.carritodotResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).carritodot(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.carritodotResponse> ProyectoCliente.servicioweb.VolumenEsfera.carritodotAsync(ProyectoCliente.servicioweb.carritodotRequest request) {
            return base.Channel.carritodotAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.carritodotResponse> carritodotAsync(string arg0) {
            ProyectoCliente.servicioweb.carritodotRequest inValue = new ProyectoCliente.servicioweb.carritodotRequest();
            inValue.Body = new ProyectoCliente.servicioweb.carritodotRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).carritodotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoCliente.servicioweb.comprarResponse ProyectoCliente.servicioweb.VolumenEsfera.comprar(ProyectoCliente.servicioweb.comprarRequest request) {
            return base.Channel.comprar(request);
        }
        
        public void comprar(string arg0) {
            ProyectoCliente.servicioweb.comprarRequest inValue = new ProyectoCliente.servicioweb.comprarRequest();
            inValue.Body = new ProyectoCliente.servicioweb.comprarRequestBody();
            inValue.Body.arg0 = arg0;
            ProyectoCliente.servicioweb.comprarResponse retVal = ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).comprar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoCliente.servicioweb.comprarResponse> ProyectoCliente.servicioweb.VolumenEsfera.comprarAsync(ProyectoCliente.servicioweb.comprarRequest request) {
            return base.Channel.comprarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoCliente.servicioweb.comprarResponse> comprarAsync(string arg0) {
            ProyectoCliente.servicioweb.comprarRequest inValue = new ProyectoCliente.servicioweb.comprarRequest();
            inValue.Body = new ProyectoCliente.servicioweb.comprarRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ProyectoCliente.servicioweb.VolumenEsfera)(this)).comprarAsync(inValue);
        }
    }
}
