//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEDDProyecto.servicioweb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Volumen/", ConfigurationName="servicioweb.ServiciosWeb")]
    public interface ServiciosWeb {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Volumen/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/CalcularVolumenEsferaRequest", ReplyAction="http://Volumen/ServiciosWeb/CalcularVolumenEsferaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse CalcularVolumenEsfera(ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/CalcularVolumenEsferaRequest", ReplyAction="http://Volumen/ServiciosWeb/CalcularVolumenEsferaResponse")]
        System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse> CalcularVolumenEsferaAsync(ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento User del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/LoginRequest", ReplyAction="http://Volumen/ServiciosWeb/LoginResponse")]
        ClienteEDDProyecto.servicioweb.LoginResponse Login(ClienteEDDProyecto.servicioweb.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Volumen/ServiciosWeb/LoginRequest", ReplyAction="http://Volumen/ServiciosWeb/LoginResponse")]
        System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.LoginResponse> LoginAsync(ClienteEDDProyecto.servicioweb.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularVolumenEsfera", WrapperNamespace="http://Volumen/", IsWrapped=true)]
    public partial class CalcularVolumenEsferaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Radio;
        
        public CalcularVolumenEsferaRequest() {
        }
        
        public CalcularVolumenEsferaRequest(double Radio) {
            this.Radio = Radio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularVolumenEsferaResponse", WrapperNamespace="http://Volumen/", IsWrapped=true)]
    public partial class CalcularVolumenEsferaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public CalcularVolumenEsferaResponse() {
        }
        
        public CalcularVolumenEsferaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://Volumen/", Order=0)]
        public ClienteEDDProyecto.servicioweb.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClienteEDDProyecto.servicioweb.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string User, string Pass) {
            this.User = User;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://Volumen/", Order=0)]
        public ClienteEDDProyecto.servicioweb.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClienteEDDProyecto.servicioweb.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWebChannel : ClienteEDDProyecto.servicioweb.ServiciosWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWebClient : System.ServiceModel.ClientBase<ClienteEDDProyecto.servicioweb.ServiciosWeb>, ClienteEDDProyecto.servicioweb.ServiciosWeb {
        
        public ServiciosWebClient() {
        }
        
        public ServiciosWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse ClienteEDDProyecto.servicioweb.ServiciosWeb.CalcularVolumenEsfera(ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest request) {
            return base.Channel.CalcularVolumenEsfera(request);
        }
        
        public double CalcularVolumenEsfera(double Radio) {
            ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest inValue = new ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest();
            inValue.Radio = Radio;
            ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse retVal = ((ClienteEDDProyecto.servicioweb.ServiciosWeb)(this)).CalcularVolumenEsfera(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse> ClienteEDDProyecto.servicioweb.ServiciosWeb.CalcularVolumenEsferaAsync(ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest request) {
            return base.Channel.CalcularVolumenEsferaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaResponse> CalcularVolumenEsferaAsync(double Radio) {
            ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest inValue = new ClienteEDDProyecto.servicioweb.CalcularVolumenEsferaRequest();
            inValue.Radio = Radio;
            return ((ClienteEDDProyecto.servicioweb.ServiciosWeb)(this)).CalcularVolumenEsferaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEDDProyecto.servicioweb.LoginResponse ClienteEDDProyecto.servicioweb.ServiciosWeb.Login(ClienteEDDProyecto.servicioweb.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string User, string Pass) {
            ClienteEDDProyecto.servicioweb.LoginRequest inValue = new ClienteEDDProyecto.servicioweb.LoginRequest();
            inValue.Body = new ClienteEDDProyecto.servicioweb.LoginRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            ClienteEDDProyecto.servicioweb.LoginResponse retVal = ((ClienteEDDProyecto.servicioweb.ServiciosWeb)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.LoginResponse> ClienteEDDProyecto.servicioweb.ServiciosWeb.LoginAsync(ClienteEDDProyecto.servicioweb.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEDDProyecto.servicioweb.LoginResponse> LoginAsync(string User, string Pass) {
            ClienteEDDProyecto.servicioweb.LoginRequest inValue = new ClienteEDDProyecto.servicioweb.LoginRequest();
            inValue.Body = new ClienteEDDProyecto.servicioweb.LoginRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pass = Pass;
            return ((ClienteEDDProyecto.servicioweb.ServiciosWeb)(this)).LoginAsync(inValue);
        }
    }
}
